### ISSUE TITLE
PHP8 related?

### ISSUE THREAD

**Issue by hroma** [natharyu/Native-PHP-MVC-With-Auth#1]
Hi, 
I really love the simplicity of your code without making compromise with efficiency  :-)

While testing, I tried to access the /dashboard page without being logged in and got the following error:

`Warning: Undefined array key "sessionKey" in C:\Site\App\Controller\Dashboard.php on line 12`

Is it related to PHP 8 where it's not allowed to check missing value? 

Line 12 of Dashboard.php : Session::isAdmin($_SESSION['sessionKey'])) doesn't exist so it throw an error...

I was also wondering how to add a 404 page if route doesn't exist.

Hope it helps to make this MVC boilerplate even better.

**Comment by natharyu** [comment]
dashboard.php error line 12 corrected and View & route for 404 error created ;) 
Check if  everything works for you. Thank you for your comment

**Comment by hroma** [comment]
Yes, everything works.
Thank you :-)
