### ISSUE TITLE
login validation issue

### ISSUE THREAD

**Issue by hroma** [natharyu/Native-PHP-MVC-With-Auth#2]
Hello,
Yes, it's me again with another bug i've found...

The application will crash on login/validate if the username doesn't exist in the database...

Steps to replicate:
1) go [https://native-php-mvc-auth.dew-dev.fr/login](https://native-php-mvc-auth.dew-dev.fr/login) 
2) enter credentials that doesn't match database records like Username: doesnotexit and Password: 1234

Result: 
redirected to https://native-php-mvc-auth.dew-dev.fr/login/validate (with blank page / crash) instead of showing an error message on the login page...

**Comment by hroma** [comment]
What if we add a check inside Database.php/getOne like

if($query->fetchColumn() > 0){ // check if an entry exist
  return $query->fetch(\PDO::FETCH_ASSOC); // if true return the data
} else {
 return []; // if false return an empty array
}

**Comment by natharyu** [comment]
hello thx for your feedback again :) validation has been patched  by using a get type of $query

**Comment by hroma** [comment]
cool
